[package]
name = "goparse"
version = "0.1.0"
authors = ["Nikita Vilunov <nikitaoryol@gmail.com>", "Ivan Lyagaev <ilsocialacc@gmail.com"]

[dependencies]
regex = "^1.0"

[dependencies.nom]
version = "^4.0"
features = ['regexp']
